version: '3.8'
services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/code
      - /code/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
